/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomRouteImport } from './routes/room'
import { Route as PlayRouteImport } from './routes/play'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinGameCodeRouteImport } from './routes/join.$gameCode'

const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinGameCodeRoute = JoinGameCodeRouteImport.update({
  id: '/$gameCode',
  path: '/$gameCode',
  getParentRoute: () => JoinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRouteWithChildren
  '/play': typeof PlayRoute
  '/room': typeof RoomRoute
  '/join/$gameCode': typeof JoinGameCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRouteWithChildren
  '/play': typeof PlayRoute
  '/room': typeof RoomRoute
  '/join/$gameCode': typeof JoinGameCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRouteWithChildren
  '/play': typeof PlayRoute
  '/room': typeof RoomRoute
  '/join/$gameCode': typeof JoinGameCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/play' | '/room' | '/join/$gameCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/play' | '/room' | '/join/$gameCode'
  id: '__root__' | '/' | '/join' | '/play' | '/room' | '/join/$gameCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRouteWithChildren
  PlayRoute: typeof PlayRoute
  RoomRoute: typeof RoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$gameCode': {
      id: '/join/$gameCode'
      path: '/$gameCode'
      fullPath: '/join/$gameCode'
      preLoaderRoute: typeof JoinGameCodeRouteImport
      parentRoute: typeof JoinRoute
    }
  }
}

interface JoinRouteChildren {
  JoinGameCodeRoute: typeof JoinGameCodeRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinGameCodeRoute: JoinGameCodeRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRouteWithChildren,
  PlayRoute: PlayRoute,
  RoomRoute: RoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
